language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --dev

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --verbose --coverage-clover=build/logs/coverage.xml

after_success:
 - travis_retry php vendor/bin/coveralls --coverage_clover build/logs/coverage.xml
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.xml
