language: php

php:
  - 7

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
 - phpunit --verbose --debug --coverage-clover=build/logs/coverage.xml

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.xml
after_success:
 - travis_retry php vendor/bin/coveralls